### ISSUE TITLE
Due to the update to OBS 29.1, UnityCapture is no longer compatible.

### ISSUE THREAD

**Issue by 7takamu** [schellingb/UnityCapture#35]
Due to the update to OBS 29.1, UnityCapture is no longer compatible. The virtual camera for UnityCapture is not appearing as an option in the "Video Capture Device" selection. Could you please provide instructions on how to display UnityCapture's virtual camera in the Video Capture Device? It was working fine in OBS versions prior to 28.1. Thank you in advance.

**Comment by meta-meta** [comment]
experiencing this as well

**Comment by schellingb** [comment]
This was solved in #33 and the latest version should appear normally again.
To update, run uninstall on the old version (which can be downloaded [`here`](../archive/7a3278dcefe37544370226e92bdfd60140434045.zip)) then install the latest version downloadable from [`here`](../archive/master.zip).

**Comment by meta-meta** [comment]
Thanks! Just finished reading that thread and testing it out now. Works like a charm!
