### ISSUE TITLE
Is there any way to change the name of the virtual device?

### ISSUE THREAD

**Issue by Straafe** [schellingb/UnityCapture#6]
Is there any way to change the name of the virtual device from "Unity Video Capture" to another name we could choose? Or is that built into the DLL's and not changeable?

**Comment by schellingb** [comment]
Hi there

I just had a few free minutes so I added a new option to the filter registering and a new `InstallCustomName.bat` file to use it.

If you want multiple devices with a custom name you need to combine what the two `.bat` files are doing.

You can even custom name each by registering them in reverse order like:
```
regsvr32 "UnityCaptureFilter64bit.dll" "/i:UnityCaptureDevices=3" "/i:UnityCaptureName=UVC THREE"
regsvr32 "UnityCaptureFilter64bit.dll" "/i:UnityCaptureDevices=2" "/i:UnityCaptureName=UVC TWO"
regsvr32 "UnityCaptureFilter64bit.dll" "/i:UnityCaptureDevices=1" "/i:UnityCaptureName=UVC ONE"
```

Hope that works for you :-)

**Comment by Straafe** [comment]
I'll try that out, looks like it should work perfectly. You're amazing, thank you for taking the time to add that in.
